name: build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

permissions:
  packages: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-bash-jq:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Bash + jq
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/rjocoleman/bash-jq:latest
          labels: |
            org.opencontainers.image.source = "https://github.com/rjocoleman/bash-jq"
          platforms: >
            linux/386,
            linux/amd64,
            linux/arm64,
            linux/arm/v6,
            linux/arm/v7,
            linux/ppc64le,
            linux/s390x
          cache-from: type=gha
          cache-to: type=gha,mode=max
